ChatAppRSA/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PerformRSA.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PerformRSA/urls.py
from django.urls import path

from . import views

app_name = 'PerformRSA'
urlpatterns = [
	path('', views.register, name='register'),
    path('send/', views.send, name='send'),
    path('home/', views.home, name='home'),
    path('home/joinRoom', views.joinRoom, name='joinRoom'),
    path('home/privateChat', views.privateChat, name='privateChat'),
    path('home/createRoom/', views.createRoom, name='createRoom'),
    path('home/createRoom/<str:room_name>/', views.room, name='room'),
    path('home/createRoom/<str:room_name>/chat-log', views.chatlog, name='chat-log'),
    path('home/createRoom/<str:room_name>/decrypt', views.decrypt, name='decrypt'),
    path('home/createRoom/<str:room_name>/verifyIdentity', views.verifyIdentity, name='verifyIdentity'),
    path('home/createRoom/<str:room_name>/putPassword', views.putPassword, name='putPassword'),
]

PerformRSA/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

bitlength_choices = (
	(128, '128 bits'),
	(256, '256 bits'),
	(512, '512 bits'),
	(1024, '1024 bits'),
	(2048, '2048 bits'),
)

roomType_choices = (
	("private", "private"),
	("public", "public"),
)


class userModel(User):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	uid = models.BigAutoField(primary_key=True)
	
	def __str__(self):
		return self.user.username

class roomModel(models.Model):
	roomId = models.BigAutoField(primary_key=True)
	roomName = models.CharField(max_length=200, unique=True)
	roomType = models.CharField(max_length=50,choices=roomType_choices, default="private")
	createdOn = models.DateTimeField(default=datetime.now, blank=False)
	password = models.CharField(max_length=100, default="")

	def __str__(self):
		return self.roomName

class createsModel(models.Model):
	uid = models.ForeignKey(userModel, on_delete=models.CASCADE) # needs to be a user
	roomId = models.ForeignKey(roomModel, on_delete=models.CASCADE) # needs to be a room 

class messageModel(models.Model):
	messageId = models.BigAutoField(primary_key=True)
	room = models.ForeignKey(roomModel, on_delete=models.CASCADE, null=True)
	text = models.TextField(blank=True, null=True)
	bits = models.IntegerField(choices=bitlength_choices, default='128')
	cipherText = models.TextField(blank=True, null=True)
	sender = models.CharField(max_length=200, default="")
	date = models.DateTimeField(default=datetime.now, editable=True)
	read = models.BooleanField(default=False)
	ctlist = models.TextField(blank=True, null=True)
	publicKey = models.TextField(blank=True, null=True)
	phi = models.TextField(blank=True, null=True)
	modulus = models.TextField(blank=True, null=True)

class roomHasMessages(models.Model):
	roomId = models.ForeignKey(roomModel, on_delete=models.CASCADE) # needs to be a room 
	messageId = models.ForeignKey(messageModel, on_delete=models.CASCADE) # needs to be a room 

PerformRSA/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import messageModel, roomModel, userModel


class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
	
	class Meta:
		model = userModel
		fields = ('username', 'first_name', 'last_name', 'password1', 'password1',)

class messageForm(forms.ModelForm):
	
	class Meta:
		model = messageModel
		fields = ('text', 'bits')

	def __init__(self, *args, **kwargs):
		super(messageForm, self).__init__(*args, **kwargs)
		self.fields['text'].widget.attrs\
			.update({
				'id': 'chat-message-input',
				'placeholder': 'Enter your message here\n\nAlways encrypt after typing your message'
			})

class roomForm(forms.ModelForm):
	class Meta:
		model = roomModel
		fields = ('roomName', 'roomType')

class passwordForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = roomModel
		fields = ('password',)

	def save(self, commit=True):
	    # Save the provided password in hashed format
	    room = super(passwordForm, self).save(commit=False)
	    room.set_password(self.cleaned_data["password"])
	    if commit:
	        room.save()
	    return room

class verificationForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = roomModel
		fields = ('password',)
	

PerformRSA/views.py
import json
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe

from . import crypt
from .forms import messageForm, roomForm, SignUpForm, passwordForm, verificationForm
from .models import messageModel, roomModel, userModel


def register(request):
	if(request.method == 'POST'):
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			uname = form.cleaned_data.get('username')
			raw_pass = form.cleaned_data.get('password1')
			user = authenticate(username=uname, password=raw_pass)
			login(request, user)
			return redirect('login')
	else:
		form = SignUpForm()
	return render(request, 'rsaDemo/register.html', {'form' : form})

@login_required
def home(request):
	return render(request, 'rsaDemo/home.html')

@login_required
def joinRoom(request):
	rooms = roomModel.objects.all()
	context = {
		'rooms' : rooms,
	}
	return render(request, 'rsaDemo/joinRoom.html', context)


def privateChat(request):
	users = userModel.objects.all()
	context = {
		'users' : users,
	}
	return render(request, 'rsaDemo/privateChat.html', context)

@login_required
def createRoom(request):
	form = roomForm(request.POST)
	if(request.method == 'POST'):
		if form.is_valid():
			roomName = form.cleaned_data['roomName']
			if not roomModel.objects.filter(roomName=roomName).exists():
				form.save()
				roomType = form.cleaned_data['roomType']
				if roomType == 'private':
					return redirect('PerformRSA:putPassword', room_name=roomName)

				messages.success(request, 'Room successfully created')
				return redirect('PerformRSA:room', room_name=roomName)
			else:
				messages.info(request, 'Room already exists')
				return redirect('PerformRSA:createRoom')
		else:
			messages.warning(request, 'Please correct the error below.')
	else:
		form = roomForm()
	return render(request, 'rsaDemo/createRoom.html', {'form': form}) 



def putPassword(request, room_name):
	room = roomModel.objects.get(roomName=room_name)
	form = passwordForm(request.POST)
	if request.method == 'POST':
		if form.is_valid():
			password = form.cleaned_data.get('password')
			room.password = password
			room.save()
			return redirect('PerformRSA:room', room_name=room_name)
	else:
		form = passwordForm()
	context = {
		'room' : room,
		'form' : form,
	}
	return render(request, 'rsaDemo/putPassword.html', context)

@login_required
def room(request, room_name):
	form = messageForm(request.POST)
	if request.method == 'POST':
		if form.is_valid():
			plaintext = form.cleaned_data['text']
			bitlength = form.cleaned_data['bits']
			form.save()
			rsaObj = messageModel.objects.get(text=plaintext)
			rsaObj.date = datetime.now()
			rsaObj.sender = request.user.username
			rsaObj.room = roomModel.objects.get(roomName=room_name)
			rsaObj.save(update_fields=['date', 'sender', 'room'])
			n, phi, private_key, public_key = crypt.runRSA(bitlength)
			ct_list, ciphertext = crypt.encrypt(plaintext, public_key, n)
			deciphered_text = crypt.decrypt(ct_list, ciphertext, private_key, n)
			rsaObj.modulus = n
			rsaObj.cipherText = ciphertext
			rsaObj.ctlist = json.dumps(ct_list)
			rsaObj.publicKey = str(public_key)
			rsaObj.phi = str(phi)
			rsaObj.save(update_fields=['modulus', 'cipherText', 'ctlist', 'publicKey', 'phi'])

			messages.success(request, "Message encrypted successfully. Your Private key is : " + str(private_key))
			context = {
				'form' : form,
				'plaintext' : plaintext,
				'ciphertext' : ciphertext,
				'ct_list' : ct_list,
				'modulus' : n,
				'phi' : phi,
				'private_key' : private_key,
				'public_key' : public_key,
				'room_name_json': (mark_safe(json.dumps(room_name))),
			}
			
	else:
		form = messageForm()
		context = {
			'form' : form,
			'room_name_json': (mark_safe(json.dumps(room_name))),
		}

	return render(request, 'rsaDemo/room.html', context)

@login_required
def send(request):
	form = messageForm(request.POST)
	
	if form.is_valid():
		plaintext = form.cleaned_data['text']
		bitlength = form.cleaned_data['bits']
		form.save()
	else:
		form = messageForm()
	context = {
		'form' : form,
	}
	return render(request, 'rsaDemo/send.html', context)

@login_required
def verifyIdentity(request, room_name):
	room = roomModel.objects.get(roomName=room_name)
	roompassword = str(room.password)
	form = verificationForm(request.POST)
	if request.method == 'POST':
		if form.is_valid():
			password = form.cleaned_data.get('password')
			if roompassword == str(password):
				return redirect('PerformRSA:room', room_name=room_name)
			else:
				messages.warning(request, 'Wrong password')
	else:
		form = verificationForm()
	context = {
		'room' : room,
		'form' : form,
	}
	return render(request, 'rsaDemo/verifyIdentity.html', context)

@login_required
def decrypt(request, room_name):
	room = roomModel.objects.get(roomName=room_name)
	messages = room.messagemodel_set.all().filter(read=False).order_by('-date')
	data = []
	if len(messages) == 0:
		flag=True
	else:
		flag=False
	print(flag)
	for item in messages:
		date_ = item.date
		date = str(date_.hour) + ":" + str(date_.minute) + ":" + str(date_.second)
		publickey_ = int(item.publicKey)
		modulus = int(item.modulus)
		totient = int(item.phi)
		cipherText_ = int(item.cipherText)
		bits = item.bits
		
		privateKey = crypt.generatePrivateKey(publickey_, totient)

		print("public key : ", publickey_)
		print("totient : ", totient)
		print("PRIVATE KEY : ", privateKey)

		jsonDec = json.decoder.JSONDecoder()
		ct_list = jsonDec.decode(item.ctlist)

		deciphered_text = crypt.decrypt(ct_list, cipherText_, privateKey, modulus)
		message_dict = {
			'ciphertext' : str(item.cipherText),
			'sender' : str(item.sender),
			'time' : str(date),
			'deciphered_text' : str(deciphered_text),
			'bits' : bits,
		}
		data.append(message_dict)
		item.read = True
		item.save(update_fields=['read'])

	context = {
		'data' : data,
		'flag' : flag,
		'room' : room_name,
	}

	print(context)

	return render(request, 'rsaDemo/decrypt.html', context)

@login_required
def chatlog(request, room_name):
	room = roomModel.objects.get(roomName=room_name)
	messages_ = room.messagemodel_set.all().filter(read=False)
	messages = room.messagemodel_set.all().filter(read=True).order_by('-date')

	if len(messages_):
		flag=True
	else:
		flag=False

	if len(messages) == 0:
		flag1=True
	else:
		flag1=False

	chat_log = []
	for item in messages:
		bits = item.bits
		sender = item.sender
		ciphertext = item.cipherText
		publicKey = item.publicKey
		time = item.date
		plaintext = item.text

		chat = {
			'bits' : bits,
			'sender' : sender,
			'ciphertext' : ciphertext,
			'publicKey' : publicKey,
			'time' : time,
			'plaintext' : plaintext,
		}

		chat_log.append(chat)
		
	context = {
		'chatlog':chat_log,
		'flag':flag,
		'flag1':flag1,
		'room' : room_name,
	}

	return render(request, 'rsaDemo/chatlog.html', context)

PerformRSA/templates/rsaDemo/chatlog.html
{% extends "base.html" %}

{% block content %}
	

	<div class="container" style="padding: 50px;">
		{% if flag %}
			<p>You have some unread messages. Decrypt the unread messages to store them in the chat log. <a href="decrypt">Click to decrypt</a></p>
			
		{% endif %}

		<h4>Chat History Of All Read Messages</h4>
		<a class="btn" href="/home/createRoom/{{room}}/" style="float: right;">Go back</a>
		{% if flag1 %}
			<div class="container center white-box" style="margin-top: 50px; width: 60%; text-align: center; padding: 30px;">No messages have been sent yet.</div>
		{% endif %}
		{% for chat in chatlog %}
			<div class="container" style="padding: 50px; margin-bottom: 10px; border: solid 1px grey; border-radius: 15px; background-color: teal;">

				<h6 style="float: left; padding: 35px;"><span style="color: orange"> {{chat.sender}}</span> </h6>
				<p style="color: yellow;">{{chat.plaintext}}</p>
				
				<div class="container">
					Encrypted using {{chat.bits}} keys | {{chat.time}}
					<hr>
					<p style="overflow: scroll;">Public key used for encryption : {{chat.publicKey}}</p>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

PerformRSA/templates/rsaDemo/createRoom.html
{% extends "base.html" %}

{% block content %}
	<div class="container center white-box" style="margin-top: 100px; width: 45%;">
		<a href="/home" style="text-decoration: none;color: yellow;float: right;">Go back</a>
		<h2>Create a chatroom!</h2>
		<hr>
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Create">
		</form>
	</div>

{% endblock %}

PerformRSA/templates/rsaDemo/decrypt.html
{% extends "base.html" %}

{% block content %}
	<div class="container center white-box" style="margin-top: 30px; width: 75%;">
		{% if flag %}
			<div class="container" style="padding: 30px;">
				<h4 style="text-align: center;">No new messages to decrypt</h4>
				<a href="/home/createRoom/{{room}}/" style="color: yellow; float: right; text-decoration: none;">Go back</a>
			</div>
		{% endif %}
		{% for element in data %}
		<div class="container" style="padding: 30px;">
			<h4 style="overflow: scroll;">Cipher Text : {{element.ciphertext}}</h4>
			<h5 style="float: right;">Sent by <span style="color: yellow;">{{element.sender}}</span> using <span style="color: orange;">{{element.bits}}</span> bit keys | Time : <span style="color: pink;">{{element.time}}</span></h5>
			<button onclick='myFunction("{{element.ciphertext}}")'>Show deciphered message</button>
			<br>

			<div class="container" id="{{element.ciphertext}}" style="display: none;">
				<hr>
				<h4>Deciphered message: <span style="color: yellow;">{{element.deciphered_text}}</span></h4>
			</div>
			<a href="/home/createRoom/{{room}}/" style="color: yellow; float: right; text-decoration: none;">Go back</a>
		</div>
		{% endfor %}
	</div>
	<script>
		function myFunction(ele) {
			var x = document.getElementById(ele);
			if (x.style.display === "none"){
			    x.style.display = "block";
			}
			else{
			    x.style.display = "none";
			}
		}



	</script>    	
{% endblock %}

PerformRSA/templates/rsaDemo/home.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<p>
	  		<a class="btn" href="{% url 'logout' %}" style="float: right; background-color: teal;">logout</a>
	  	</p>
	</div>
	<div class="ml-6" style="padding: 50px;">
	{% if user.is_authenticated %}
		<div class="container">
	  		<h2>Hi <span style="color: pink;">{{ user.username }}</span>, welcome to Secure Chat!</h2>
	  	</div>
	  	<hr>
	  	<div class="row">
	  		
		  	<div class="col-sm-4 cool-link">
		  		<a style="text-decoration:none;"  href="{% url 'PerformRSA:home' %}createRoom">
		  		<div class="square">
				  	<h4 style="text-align: center;color: yellow; margin-left: 70px;">Create room</h4>
		  		</div>
		  		</a>
		  	</div>
		  	

		  	<div class="col-sm-4 cool-link">
		  		<a style="text-decoration:none;" href="{% url 'PerformRSA:home' %}joinRoom">
		  		<div class="square" >
				  	<h4 style="text-align: center;color: yellow; margin-left: 80px;">Join room</h4>
		  		</div>
		  		</a>
		  	</div>

		  	<div class="col-sm-4 cool-link">
		  		<a style="text-decoration:none;" href="{% url 'PerformRSA:home' %}privateChat">
		  		<div class="square" >
				  	<h4 style="text-align: center;color: yellow; margin-left: 40px;">Registered Users</h4>
		  		</div>
		  		</a>
		  	</div>

		</div>

	{% else %}
		<div class="container">
		  <p>You are not logged in</p>
		  <a href="{% url 'login' %}">login</a>
		</div>
	{% endif %}
	</div>
	
	
{% endblock %}

PerformRSA/templates/rsaDemo/index.html
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Generate Public Key">
</form>

PerformRSA/templates/rsaDemo/joinRoom.html
{% extends 'base.html' %}

{% block content %}
<div class="container center white-box" style="margin-top: 40px; width: 70%;">
	<a href="/home" style="text-decoration: none;color: yellow;float: right;">Go back</a>
	<div class="row">
		<div class="col-sm-6">
	  	<h4 style="text-align: center;">Private Chatrooms</h4>
	  	<hr>
	  	{% for room in rooms %}
		  	{% if room.roomType == 'private' %}
		  		<ul>
		  			<li>
		  				<strong style="color: yellow;">{{room.roomName}}</strong>
		  				<a href="{% url 'PerformRSA:createRoom' %}{{room.roomName}}/verifyIdentity" style="float: right; text-decoration: none;">Request access</a>
		  			</li>
		  		</ul>
		  	{% endif %}
		{% endfor %}
		</div>

		<div class="col-sm-6">
	  	<h4 style="text-align: center;">Public Chatrooms</h4>
	  	<hr>
	  	{% for room in rooms %}
		  	{% if room.roomType == 'public' %}	
		  		<ul>
		  			<li>
		  				<strong style="color: yellow;">{{room.roomName}}</strong>
		  				<a href="{% url 'PerformRSA:createRoom' %}{{room.roomName}}" style="float: right; text-decoration: none;">Join Now</a>
		  			</li>
		  		</ul>
		  	{% endif %}
		{% endfor %}
		</div>
	</div>
</div>


{% endblock %}

PerformRSA/templates/rsaDemo/privateChat.html
{% extends 'base.html' %}

{% block content %}
<div class="container center white-box" style="margin-top: 80px; padding: 30px;">
	<h4>Registered users</h4>
	<hr>
	<ul style="text-decoration: none;">
		{% for user in users %}
			<li><strong>{{user.username}}</strong></li>
		{% endfor %}
	</ul>
	<a href="/home" style="text-decoration: none;color: yellow;">Go back</a>
</div>

{% endblock %}

PerformRSA/templates/rsaDemo/putPassword.html
{% extends "base.html" %}

{% block content %}
	
	<div class="container center white-box" style="margin-top: 100px; width: 60%;">
		<h4>A private room <span style="color: yellow;">{{room.roomName}}</span> has been created</h4>
		<hr>
		<h6>Create a new password</h6>
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Submit">
		</form>

	</div>

{% endblock %}

PerformRSA/templates/rsaDemo/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}Secure Chat{% endblock %}

{% block content %}
	<div class="container center white-box" style="margin-top: 30px;">
		<h2>Sign Up</h2>
		<hr>
		<form method="POST">
			{% csrf_token %}

			{% for field in form %}
			  <p>
			    {{ field.label_tag }}<br>
			    {{ field }}
			    {% for error in field.errors %}
			      <p style="color: yellow;">{{ error }}</p>
			    {% endfor %}
			  </p>
			{% endfor %}
			<input type="submit" value="Sign Up">
			<hr>
			<div class="ml-4">
				<small>Already have an account? <a style="color: yellow;" href="{% url 'login' %}">login</a></small>
			</div>
		</form>
	</div>

{% endblock %}

PerformRSA/templates/rsaDemo/room.html
{% extends "base.html" %}

<head>
    <meta charset="utf-8"/>
    <title>{{ room_name_json }}</title>
</head>

{% block content %}
    <div class="container" style="padding: 20px;width: 110%">
        <h4>Secure Chat | <span style="color: yellow;">{{user.username}}</span>-------------------------------------------------------------<small><a href="/home" style="text-decoration: none; color: pink;">Home</a></small></h4>

        <div class="row">
            <div class="col-sm-6">
                <textarea id="chat-log" cols="60" rows="16"></textarea><br/>
            </div>
            <div class="col-sm-6" >
                <form method="POST" style="background-color: teal; padding: 20px;">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn" type="submit" value="Encrypt message" style="color: black; background-color: white; border-radius: 10px;">
                </form>
            </div>
        </div>
        <div class="container">
                <input class="btn btn-danger" id="chat-message-submit" type="button" value="Send Encrypted message">

                <a href="decrypt" class="btn btn-danger" type="button">Decrypt message</a>
                <br><br>
                <div class="row" style="background-color: white; padding: 15px;">
                    <div class="col-sm-6">
                        <p style="color: black; text-align: center;">To view your chat history <a style="color: red;" href="chat-log">click here</a></p>
                    </div>
                    <div class="col-sm-6">
                        <p style="color: black;text-align: center;">You can logout by clicking <a style="color: red;" href="{% url 'logout' %}">here</a></p>
                    </div>
                </div>

       </div>
    </div>

    
    <script>
        var roomName = {{ room_name_json }};

        var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/chat/' + roomName + '/');

        chatSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            var message = data['message'];
            document.querySelector('#chat-log').value += (message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        //Focus the input area to type, 
        document.querySelector('#chat-message-input').focus();

        //Typing inside the input area
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                //on clicking the submit button, run the below function
                document.querySelector('#chat-message-submit').click();
            }
        };


        document.querySelector('#chat-message-submit').onclick = function(e) {
            time = new Date();
            var val = "AM";
            hours = time.getHours();
            if(hours == 0){
                hours = 12;
                val = "AM";
            }
            if(hours > 12){
                hours = hours-12;
                val = "PM";
            }

            mins = time.getMinutes();
            secs = time.getSeconds();

            var messageInputDom = document.querySelector('#chat-message-input');
            var u = "{{user.username}}";
            var message = "Message sent by " + u + " at time " + hours + ':' + mins + ':' + secs + " " + val + "\n\n";
            message += "Public key so generated is\t {{public_key}}\n\n";
            message += "The modulus of RSA is\t {{modulus}}\n\n";
            message += "Euler's Totient is\t {{phi}}";
            message += "\n\nThe cipher text generated using RSA is\t {{ciphertext}}\n";

            chatSocket.send(JSON.stringify({
                'message': message
            }));

            messageInputDom.value = '';
        };

    </script>
{% endblock %}

PerformRSA/templates/rsaDemo/send.html
{% extends "base.html" %}

{% block content %}
	{% if user.is_authenticated %}
		<div class="container">
	  		Hi {{ user.username }}!
	  	</div>
	  	
	  	<div class="container">
			<form method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<input type="submit" value="Generate Public Key">
			</form>
		</div>

		<p>
	  		<a href="{% url 'logout' %}">logout</a>
	  	</p>
	  	
	{% else %}
	  <p>You are not logged in</p>
	  <a href="{% url 'login' %}">login</a>
	{% endif %}
	
{% endblock %}

PerformRSA/templates/rsaDemo/verifyIdentity.html
{% extends "base.html" %}

{% block content %}

	<div class="container center white-box" style="margin-top: 30px; width: 70%">
		<h4>Enter the password to gain access to the room <span class="text-primary"></span>{{room.roomName}}</h4>
			<hr>
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Submit">
            <a href="/home" style="text-decoration: none;color: yellow;">Go back</a>
		</form>
	</div>

{% endblock %}